# Generated by Django 3.2.8 on 2021-10-25 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 21, 57, 28, 826699), verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('addres', models.CharField(max_length=500, unique=True, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Room type',
                'verbose_name_plural': 'Room types',
                'db_table': 'hotels_roomtypes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('phone1', models.CharField(blank=True, max_length=255, verbose_name='phone 1')),
                ('seats_base', models.PositiveIntegerField(default=1, verbose_name='seats base')),
                ('seats_additional', models.PositiveIntegerField(default=0, verbose_name='seats additional')),
                ('booked', models.BooleanField(default=False, verbose_name='booked Room')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HotelesCore.hotel', verbose_name='hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HotelesCore.roomtype', verbose_name='room type')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'hotels_rooms',
                'ordering': ['hotel', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='user')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HotelesCore.hotel', verbose_name='hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HotelesCore.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'hotels_rooms_booking',
                'ordering': ['room', 'id'],
            },
        ),
    ]
