# Generated by Django 3.2.8 on 2021-10-25 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelesCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 22, 3, 24, 329285), verbose_name='Fecha de creacion'),
        ),
    ]
