# Generated by Django 3.2.8 on 2021-10-27 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelesCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de actualizacion'),
        ),
    ]
