# Generated by Django 3.2.8 on 2021-10-25 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelesCore', '0002_alter_hotel_crated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creacion'),
        ),
    ]
